version: '3.8'
services:
  simple_timecard:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./:/workspace"
    ports:
      - "3000:3000"
    tty: true
    command: sh -c "npm run build; npm run dev"
